// Copyright (C) 2013 Christopher "Kasoki" Kaster (@Kasoki)
// 
// This file is part of "SWT-Realtime". <http://github.com/Kasoki/SWT-Realtime>
//
// Neither this library nor the author are somehow related to SWT (Stadtwerke Trier)!
// 
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
// THE SOFTWARE.
package de.kasoki.swtrealtime;

public enum BusStop {
	// This list was automatic generated, if you find any mistakes please correct them! Thanks :)
	AACHENERSTR("aache", "Aachener Str."),
	ADASTR("adast", "Adastr."),
	ADOLPHKOLPINGSTR("kolpi", "Adolph-Kolping-Str."),
	AGROBSTR("agrob", "Agrobstr."),
	ALBEROWEG("alber", "Alberoweg"),
	ALTEROLLBAHN("rollb", "Alte Rollbahn"),
	ALTENHEIMHAERENWIES("ALH", "Altenheim Haerenwies"),
	ALTERORTSKERN("ortsk", "Alter Ortskern"),
	AMBEUTELWEG("beute", "Am Beutelweg"),
	AMBILDSTOCK("bilds", "Am Bildstock"),
	AMHERRENBRUENNCHEN("hbrue", "Am Herrenbruennchen"),
	AMKIEWELSBERG("kiewe", "Am Kiewelsberg"),
	AMMARIAHOF("MAH", "Am Mariahof"),
	AMMOSELKAI("mosel", "Am Moselkai"),
	AMMUEHLENTEICH("teich", "Am Muehlenteich"),
	AMSANDBACH("sandb", "Am Sandbach"),
	AMWASSERTURM("wturm", "Am Wasserturm"),
	AMWEIDENGRABENANFANG("wgran", "Am Weidengraben Anfang"),
	AMWEIDENGRABENENDE("WGR", "Am Weidengraben Ende"),
	AMWEIDENGRABENMITTE("wgrmi", "Am Weidengraben Mitte"),
	AMWISSENSCHAFTSPARK("wpark", "Am Wissenschaftspark"),
	AMALTENFLUGPLATZ("flugp", "Am alten Flugplatz"),
	AMPHITHEATER("amphi", "Amphitheater"),
	ANDERFELDPORT("feldp", "An der Feldport"),
	ANDERMAESWIES("maesw", "An der Maeswies"),
	ANDERPFERDSWEIDE("weide", "An der Pferdsweide"),
	ANDERSCHULE("TRS", "An der Schule"),
	ANDERZIEGELE("ziege", "An der Ziegele"),
	ANDREASSTR("taran", "Andreasstr."),
	ANHEIERSTR("anhei", "Anheierstr."),
	ARENATRIER("arena", "Arena Trier"),
	ARNOLDISTR("arnol", "Arnoldistr."),
	AUFMOHRBUESCH("mohrb", "Auf Mohrbuesch"),
	AUFDEMKIRCHSPIEL("kirch", "Auf dem Kirchspiel"),
	AUFDERBAUSCH("BAU", "Auf der Bausch"),
	AUFDERHILL("HIL", "Auf der Hill"),
	AUFDERJUENG("jueng", "Auf der Jueng"),
	AUGUSTASTR("augus", "Augustastr."),
	AVELERHOF("avhof", "Avelerhof"),
	BALDUINSBRUNNENHBF("baldu", "Balduinsbrunnen/HBF"),
	BARBARATHERMEN("barth", "Barbarathermen"),
	BARBARAUFERROEMERBRUECKE("baruf", "Barbaraufer/Roemerbruecke"),
	BEHRINGSTR("behri", "Behringstr."),
	BENEDIKTINERSTR("bened", "Benediktinerstr."),
	BERGSTR("bergs", "Bergstr."),
	BERNHARDSTR("bernh", "Bernhardstr."),
	BERTAR("berta", "Bertar"),
	BETTEMBURGSTR("bette", "Bettemburgstr."),
	BIEWERNORD("bnord", "Biewer-Nord"),
	BIEWERSUED("bsued", "Biewer-Sued"),
	BITBURGERSTR("bitbu", "Bitburger Str."),
	BLUECHERSTR("bluec", "Bluecherstr."),
	BLUETENWEG("bluet", "Bluetenweg"),
	BONHOCHWALDSTR("bohoc", "Bon-Hochwaldstr."),
	BONNEUSTR("boneu", "Bon-Neustr."),
	BONTALSPERRENBLICK("BON", "Bon-Talsperrenblick"),
	BONIFATIUSSTR("bonif", "Bonifatiusstr."),
	BONNERSTR("bst", "Bonner Str."),
	BRETTENBAC("brett", "Brettenbac"),
	BRUCHHAUSENSTR("bhaus", "Bruchhausenstr."),
	BUCHENWEG("buche", "Buchenweg"),
	BURGMUEHLENSTR("burgm", "Burgmuehlenstr."),
	CASPAROLEVIANSTR("caspa", "Caspar-Olevian-Str."),
	CASTELFORT("CAS", "Castelfort"),
	CHARLOTTENSTR("charl", "Charlottenstr"),
	CLARAVIEBIGSTR("viebi", "Clara-Viebig-Str"),
	CUSANUSSTR("cusan", "Cusanusstr"),
	DEUTSCHHERRENSTR("deuts", "Deutschherrenstr"),
	DIEDENHOFENERSTR("diede", "Diedenhofener Str."),
	DOMAENENSTR("domae", "Domaenenstr"),
	DONAUSTR("donau", "Donaustr"),
	EHRANGBAHNHOF("egbhf", "Ehrang-Bahnhof"),
	EHRANGHINTEREHEIDE("EGH", "Ehrang-Hintere Heide"),
	EHRANGSCHULE("egsch", "Ehrang-Schule"),
	EHRANGSPORTPLATZ("sport", "Ehrang-Sportplatz"),
	EHRANGUNTERFUEHRUNG("EGU", "Ehrang-Unterfuehrung"),
	EHRANGERSTR("egstr", "Ehranger Str"),
	EISENBAHNSTR("eisen", "Eisenbahnstr"),
	EITELSBACHMITTE("eitel", "Eitelsbach Mitte"),
	EURENFRIEDHOF("EUF", "Euren-Friedhof"),
	EURENHELENENBRUNNEN("EUH", "Euren-Helenenbrunnen"),
	EURENLUSTEINBSTR("EUL", "Euren-Lu.Steinb.Str"),
	FACHHOCHSCHULE("FHS", "Fachhochschule"),
	FANDELBOR("fande", "Fandelbor"),
	FELDSTRMUTTERHAUS("felds", "Feldstr./Mutterhaus"),
	FEYENGRAFSCHAFT("FEY", "Feyen-Grafschaft"),
	FILSCHMITTE("fimit", "Filsch Mitte"),
	FILSCHERHAEUSCHE("FIL", "Filscher Haeusche"),
	FISCHWEG("fiweg", "Fischweg"),
	FRANZBUSSSTR("fbuss", "Franz-Buss-Str."),
	FRANZGEORGSTR("fgeor", "Franz-Georg-Str."),
	FREIHERRVSTEINSTR("freih", "Freiherr-v.Stein-Str."),
	FRIEDHOFSTR("fried", "Friedhofstr"),
	FRITZQUANTSTR("quant", "Fritz-Quant-Str"),
	FRITZVONWILLESTR("wille", "Fritz-von-Wille-Str"),
	FROEBELSTR("froeb", "Froebelstr"),
	FROEHLICHERSTR("froeh", "Froehlicherstr"),
	GAMBRINUSSTR("gambr", "Gambrinusstr"),
	GARTENFELDSTR("gfeld", "Gartenfeldstr"),
	GEORGSTR("georg", "Georgstr"),
	GILBERTSTR("GIL", "Gilbertstr"),
	GOTTBILLSTR("VB", "Gottbillstr"),
	GRAFREGINARSTR("grafr", "Graf-Reginar-Str"),
	GUSIMBILSEN("gubil", "Gus-Im Bilsen"),
	GUSIMFLUERCHE("guflu", "Gus-Im Fluerche"),
	GUSLAERCHENWEG("gulae", "Gus-Laerchenweg"),
	GUSLINDENSTR("gulin", "Gus-Lindenstr"),
	GUSROMIK("gurom", "Gus-Romik"),
	GUSRUWERSTR("guruw", "Gus-Ruwerstr"),
	GUSSCHULE("gusch", "Gus-Schule"),
	GUSSOMMERAUERSTR("gusom", "Gus-Sommerauer Str"),
	GUSTRIERERSTR("GUS", "Gus-Trierer Str"),
	GUTENBERGSTR("ZEG", "Gutenbergstr"),
	GUTWEILERIMBOORFELD("GUT", "Gutweiler-Im Boorfeld"),
	GUTWEILERKIRCHE("gtkir", "Gutweiler-Kirche"),
	HAENDELSTR("haend", "Haendelstr"),
	HAFENSTR("hafst", "Hafenstr"),
	HANDWERKSKAMMER("HWK", "Handwerkskammer"),
	HANSBOECKLERALLE("hansb", "Hans-Boeckler-Alle"),
	HANSMSCHLEYERSTR("hansm", "Hans-M.Schleyer-Str"),
	HAUPTBAHNHOF("HBF", "Hauptbahnhof"),
	HAUPTFRIEDHOF("haupt", "Hauptfriedhof"),
	HEIDESTUFE("heist", "Heidestufe"),
	HEILIGKTREVERERST("HKT", "Heiligk.-Trevererst"),
	HELENENSTR("helen", "Helenenstr"),
	HINZENBURGMITTE("HIN", "Hinzenburg Mitte"),
	HOCHWALDSTR("hochw", "Hochwaldstr"),
	HOCKWEILERMITTE("HOK", "Hockweiler Mitte"),
	HOEHENFRIEDHOF("hofri", "Hoehenfriedhof"),
	HOFBER("hofbe", "Hofber"),
	HOLZERATHMITTE("holze", "Holzerath Mitte"),
	HONTHEIMSTR("honth", "Hontheimstr"),
	HOSPITALSMUEHL("hospi", "Hospitalsmuehl"),
	HUNSRUECKSTR("hunsr", "Hunsrueckstr"),
	IGELAMFEILENKREU("igfei", "Igel-Am Feilenkreu"),
	IGELAMRODERKAM("igrod", "Igel-Am Roderkam"),
	IGELAMSCHLEIDBER("igsbe", "Igel-Am Schleidber"),
	IGELIGELERSAEUL("igsae", "Igel-Igeler Saeul"),
	IGELKIRCHE("igkir", "Igel-Kirche"),
	IGELLAUBENSTR("iglau", "Igel-Laubenstr"),
	IGELMOSELSTR("IGL", "Igel-Moselstr"),
	IGELROEMERSTR("igroe", "Igel-Roemerstr"),
	IGELSCHAUINSLAN("igsch", "Igel-Schauinslan"),
	IGELWALDSTR("igwa", "Igel-Waldstr"),
	IMAVELERTAL("avtal", "Im Avelertal"),
	IMHOPFENGARTEN("HOP", "Im Hopfengarten"),
	IMPAULINSGARTEN("RUP", "Im Paulinsgarten"),
	IMPFLANZGARTEN("pflan", "Im Pflanzgarten"),
	IMSCHAMMA("scham", "Im Schamma"),
	IMSIEBENBOR("siebe", "Im Siebenbor"),
	INDUSTRIEGEBZEWEN("IZE", "Industriegeb-Zewen"),
	IRSCHABZWEI("irabz", "Irsch Abzwei"),
	IRSCHHOCKWEILERSTR("IRH", "Irsch-Hockweilerstr"),
	IRSCHPROPSTE("IRP", "Irsch-Propste"),
	IRSCHERBERG("iberg", "Irscher Berg"),
	IRSCHERHOF("irhof", "Irscher Hof"),
	IRSCHERMUEHLE("irmue", "Irscher Muehle"),
	IRSCHERSTR("irstr", "Irscher Str."),
	ISBRUNNEN("isbru", "Is-Brunnen"),
	ISBRUNNENSTR("isbst", "Is-Brunnenstr"),
	ISZURKIESGRUBE("iskie", "Is-Zur Kiesgrube"),
	JAKOBKNEIPSTR("KEJ", "Jakob-Kneip-Str"),
	JANUARIUSZICKSTR("jzick", "Januarius-Zick-Str"),
	JOSEPHHAYDNSTR("haydn", "Joseph-Haydn-Str"),
	JUNGENWALD("jwald", "Jungenwald"),
	KAISERTHERMEN("KTH", "Kaiserthermen"),
	KANTSTR("kants", "Kantstr"),
	KANZELSTR("ZEK", "Kanzelstr"),
	KARLMARXHAUS("KMH", "Karl-Marx-Haus"),
	KARLSWEG("karls", "Karlsweg"),
	KARRENBACH("karre", "Karrenbach"),
	KASBAHNHOF("kabhf", "Kas-Bahnhof"),
	KASBAHNHOFSTR("kabst", "Kas-Bahnhofstr"),
	KASGEMEINDEPLAT("KAG", "Kas-Gemeindeplat"),
	KASHAUSTIMPER("katim", "Kas-Haus Timper"),
	KASSCHULE("kasch", "Kas-Schule"),
	KASSPORTPLAT("kaspo", "Kas-Sportplat"),
	KASWASSERHAEUSCHE("kawas", "Kas-Wasserhaeusche"),
	KENNERWEG("kenne", "Kenner Weg"),
	KERNSCHHOEHENWEG1("hoeh1", "Kernsch.Hoehenweg 1"),
	KERNSCHHOEHENWEG2("hoeh2", "Kernsch.Hoehenweg 2"),
	KERNSCHEIDKIRCHE("KER", "Kernscheid-Kirche"),
	KEUNEGRUNDSCHULE("KEU", "Keune Grundschule"),
	KLEEBURGERWEG("OLK", "Kleeburger Weg"),
	KOHLENSTR("kohle", "Kohlenstr"),
	KOLONNENWEG("KOL", "Kolonnenweg"),
	KONRADADENAUERBRUECKE("adebr", "Konrad-Adenauer-Bruecke"),
	KONSTANTINBASILIK("KON", "Konstantin Basilik"),
	KONZERSTR("konze", "Konzer Str"),
	KORLNEUSTR("koneu", "Korl-Neustr"),
	KORLZUMSTEINBRUCH("koste", "Korl-Zum Steinbruch"),
	KREUZFLUR("kreuz", "Kreuzflur"),
	KUERENZERSTR("KUE", "Kuerenzer Str"),
	KUNOSTAPELSTR("kunos", "Kuno-Stapel-Str"),
	KURFUERSTENSTR("kurfu", "Kurfuerstenstr"),
	KYRIANDERSTR("kyria", "Kyrianderstr"),
	LERHARDRINGAUSST("ludwi", "L.Erhard-Ring,Ausst"),
	LAMBERTISTR("lambe", "Lambertistr"),
	LANIMBUNGER("lgbun", "Lan-Im Bunger"),
	LANKIRCH("lgkir", "Lan-Kirch"),
	LANLOEWENERMUEHLE("lgloe", "Lan-Loewener Muehle"),
	LANMESENICHERSTR("lgmes", "Lan-Mesenicher Str"),
	LANNEUSTR("lgneu", "Lan-Neustr"),
	LANWASSERBILLIGERB("lgwas", "Lan-Wasserbilligerb"),
	LANGFLUR("langf", "Langflur"),
	LAYWEG("EGL", "Layweg"),
	LEBENSHILFE("LWT", "Lebenshilfe"),
	LENUSMARSSTR("lenus", "Lenus-Mars-Str"),
	LEVELINGSTR("level", "Levelingstr"),
	LIERSBERGHEINTZHOF("lihei", "Liersberg-Heintzhof"),
	LIERSBERGKIRCHE("LIE", "Liersberg-Kirche"),
	LOEBSTR("loebs", "Loebstr"),
	LUDWIGSIMONSTR("simon", "Ludwig-Simon-Str"),
	LUXEMBURGERSTR("luxem", "Luxemburger Str"),
	MAARSTR("maars", "Maarstr"),
	MAEUSHECKERSCHULE("MHS", "Maeusheckerschule"),
	MAEUSHECKERWE("MHW", "Maeusheckerwe"),
	MAGNERICHSTR("magne", "Magnerichstr"),
	MARIENHOLZSTR("mholz", "Marienholzstr"),
	MARIENKRANKENHAUS("mkrhs", "Marienkrankenhaus"),
	MARIENSAEULE("saeul", "Mariensaeule"),
	MARKUSBER("mberg", "Markusber"),
	MARKUSSTR("marku", "Markusstr"),
	MARTINSCHUNCKSTR("schun", "Martin-Schunck-Str"),
	MARTINSTR("marti", "Martinstr"),
	MAXIMINERACH("maxim", "Maximinerach"),
	MEILENSTR("meile", "Meilenstr"),
	MERTABZWEITELSBACH("OVB", "Mert-Abzw.Eitelsbach"),
	MERTBERGSTR("meber", "Mert-Bergstr"),
	MERTDORFBRUNNEN("medor", "Mert-Dorfbrunnen"),
	MERTEICHGRABEN("MEE", "Mert-Eichgraben"),
	MERTGRUENHAUS("megru", "Mert-Gruenhaus"),
	MERTSTADIONSTR("mesta", "Mert-Stadionstr"),
	MERTZURFESTUNG("mefes", "Mert-Zur Festung"),
	MESENICHKIRCHE("mskir", "Mesenich-Kirche"),
	MESENICHTRIERERSTR("mstri", "Mesenich-Trierer Str."),
	MESSEPARKP_PLUS("MES", "Messepark P+"),
	METZERALLE("MEZ", "Metzer Alle"),
	MOHRENKOP("MOR", "Mohrenkop"),
	MONAISERSTR("monai", "Monaiser Str"),
	MORSCHEIDMITT("MOS", "Morscheid Mitt"),
	MOSELSTADIO("stadio", "Moselstadio"),
	MUEHLENSTR("muehl", "Muehlenstr"),
	MUSTORSTR("musto", "Mustorstr"),
	MZKIRCHE("MZK", "Mz-Kirche"),
	MZWINTERSDORFERSTR("mzwin", "Mz-Wintersdorfer Str"),
	NELLSPARK("NPA", "Nells Park"),
	NELLSPARKPARKSTR("npapa", "Nells Park/Parkstr"),
	NELLSTR("nells", "Nellstr"),
	NIEDERKIRCHERSTR("nieder", "Niederkircher Str"),
	NIEDERSTR("niest", "Niederstr"),
	NIKOLAUSKOCHPLATZ("NIK", "Nikolaus-Koch-Platz"),
	NORDALLEEKRANKENHAUS("norda", "Nordallee/Krankenhaus"),
	NORDBAD("nordb", "Nordbad"),
	P_AND_R_TRIERNORD("prnor", "P+R Trier Nord"),
	PALLIENERSTR("palli", "Palliener Str"),
	PELLINGERSTR("pelli", "Pellinger Str"),
	PETERROTHPLATZ("PRP", "Peter-Roth-Platz"),
	PETERWUSTSTR("pwust", "Peter-Wust-Str"),
	PETRISBERG("PET", "Petrisberg"),
	PETRISBERGAUSSICH("aussi", "Petrisberg-Aussich"),
	PFALZELBAHNHOF("pfbhf", "Pfalzel-Bahnhof"),
	PFALZELELTZSTR("PFA", "Pfalzel-Eltzstr"),
	PFERDEMARK("markt", "Pferdemark"),
	PHILOSOPHENWEG("philo", "Philosophenweg"),
	PLUBAHNHOF("plbhf", "Plu-Bahnhof"),
	PLUBAHNHOFSTR("plbst", "Plu-Bahnhofstr"),
	PLUGUSTERATHERSTR("plgus", "Plu-Gusterather Str"),
	PLUINDWEIDENWIESE("plwei", "Plu-In d. Weidenwiese"),
	PLURUWERSTR("PLU", "Plu-Ruwerstr"),
	PORTANIGRA("PN", "Porta Nigra"),
	QUINTSCHLOSS("QUI", "Quint-Schloss"),
	QUINTERSTR("quist", "Quinter Str"),
	RATHAUSSTADTTHEATER("ratha", "Rathaus/Stadttheater"),
	REMIGIUSSTR("remig", "Remigiusstr"),
	RETZGRUBENWEG("retzg", "Retzgrubenweg"),
	RINGSTR("rings", "Ringstr"),
	RIVBAUSBACH("ribau", "Riv-Bausbach"),
	RIVMORSCHEIDERST("rimor", "Riv-Morscheider Str."),
	RIVERISMITTE("rimit", "Riveris Mitte"),
	ROEMERSTR("roest", "Roemerstr"),
	ROTBACHSTR("ROT", "Rotbachstr"),
	ROTHILDISSTR("rothi", "Rothildisstr"),
	RUBENSTR("ruben", "Rubenstr"),
	RUDOLFDIESELSTR("diese", "Rudolf-Diesel-Str"),
	RUWERBAHNHOF("rubhf", "Ruwer-Bahnhof"),
	RUWERSPORTPLATZ("RUS", "Ruwer-Sportplatz"),
	RUWERERSTR("rustr", "Ruwererstr"),
	SWTSTADTWERKETRIER("swtri", "SWT Stadtwerke Trier"),
	SCHEFFELSTR("schef", "Scheffelstr"),
	SCHIFFSTR("schif", "Schiffstr"),
	SCHLOSSSTR("schlo", "Schlossstr"),
	SCHOENBORNSTR("schoe", "Schoenbornstr"),
	SCHUETZENSTR("schue", "Schuetzenstr"),
	SCHWARZERWEG("schwa", "Schwarzer Weg"),
	SDALTENWEG("sdalt", "Sd-Altenweg"),
	SDHAUPTSTR("sdhau", "Sd-Hauptstr"),
	SDKIRCHE("sdkir", "Sd-Kirche"),
	SDPLUWIGERHAMME("plham", "Sd-Pluwigerhammer"),
	SEIFERSTR("seife", "Seiferstr"),
	SPIROSTR("spiro", "Spirostr"),
	STMATTHIA("MAT", "St. Matthia"),
	STMEDAR("MED", "St. Medar"),
	STPAULI("pauli", "St. Pauli"),
	STURBA("urban", "St. Urba"),
	STANNASTR("annas", "St.-Anna-Str"),
	STMATTHIASAULSTR("matau", "St.-Matthias-Aulstr"),
	STMATTHIASKIRCH("matki", "St.-Matthias-Kirch"),
	STMERGENERSTR("merge", "St.-Mergener-Str"),
	STADTBIBLIOTHE("bibli", "Stadtbibliothe"),
	STEFANANDRESSTR("andre", "Stefan-Andres-Str"),
	STEINBRUECKSTR("stein", "Steinbrueckstr"),
	STEINSWEG("stweg", "Steinsweg"),
	STRASSBURGERALLE("strass", "Strassburger Alle"),
	SUEDALLEEKAISERSTR("SUE", "Suedallee/Kaiserstr"),
	SUEDBAHNHOF("SBF", "Suedbahnhof"),
	SUEDFRIEDHOF("suedf", "Suedfriedhof"),
	SWALTESWEINHAU("swwei", "Sw-Altes Weinhau"),
	SWBAHNHOFSTR("swbah", "Sw-Bahnhofstr"),
	SWBERTRADASTR("swber", "Sw-Bertradastr"),
	SWBRUNNE("swbru", "Sw-Brunne"),
	SWERMESGRABE("swerm", "Sw-Ermesgrabe"),
	SWLANGFUHRSTR("SWE", "Sw-Langfuhrstr"),
	TARFKCARSTENSST("TAK", "Tarf.-K.Carstens-St"),
	TARFLERHARDRIN("TAL", "Tarf.-L.Erhard-Rin"),
	TARFORSTERSTR("tarst", "Tarforster Str"),
	TAUBENBER("taube", "Taubenber"),
	TEMPELHERRENSTR("teher", "Tempelherrenstr"),
	TEMPELWE("teweg", "Tempelwe"),
	THEODORHEUSSALLE("THA", "Theodor-Heuss-Alle"),
	THYRSUSSTR("thyrs", "Thyrsusstr"),
	TIERGARTE("OLT", "Tiergarte"),
	TOEPFERSTR("toepf", "Toepferstr"),
	TREBETASTR("trebe", "Trebetastr"),
	TREVIRS("TRV", "Treviris"),
	TRIERGALERIE("galer", "Trier Galerie"),
	TRIERERHAFEN("hafen", "Trierer Hafen"),
	TRIERWEILERWEG("TWW", "Trierweilerweg"),
	TRIMHOFAUGUSTSTR("TRH", "Trim.Hof-August.str"),
	UNIVERSITAET("UNI", "Universitaet"),
	UNIVERSITAETCAMPUS("UC2", "Universitaet Campus"),
	UNIVERSITAETHAUPTG("UNH", "Universitaet Hauptg"),
	UNIVERSITAETMENSA("UNM", "Universitaet Mensa"),
	UNIVERSITAETPARKPLATZ("unipa", "Universitaet Parkplatz"),
	UNIVERSITAETSUED("UNS", "Universitaet Sued"),
	VBREALMARK("vbrea", "VB-Real-Mark"),
	VBTESTPLAT("vbtes", "VB-Testplat"),
	VBTOR("vbto3", "VB-Tor "),
	VBZENTRAL("vbzen", "VB-Zentral"),
	VILLAREVERCHO("villa", "Villa Revercho"),
	VORDEREHEID("vheid", "Vordere Heid"),
	WALDAMSPORTPLAT("WAL", "Wald-Am Sportplat"),
	WALDAUFDEMFLUERCHE("waflu", "Wald-Auf dem Fluerche"),
	WALDBAHNHOF("wabhf", "Wald-Bahnhof"),
	WALDGEMEINDEPLAT("wagem", "Wald-Gemeindeplat"),
	WALDGEWERBEGEBIE("wagew", "Wald-Gewerbegebie"),
	WALDINDERACH("waach", "Wald-In der Ach"),
	WALDINDERLA("walay", "Wald-In der La"),
	WALDOBEREKIRCHST("wakir", "Wald-Obere Kirchst"),
	WALDPAETSCHERWE("wapae", "Wald-Paetscher We"),
	WALDROSENBUNGER("waros", "Wald-Rosenbunger"),
	WALDSCHUL("wasch", "Wald-Schul"),
	WALDWEINBERGSWEG("wawei", "Wald-Weinbergsweg"),
	WALDZOLLWE("wazol", "Wald-Zollwe"),
	WALDSTR("walds", "Waldstr"),
	WALLENBACHSTR("walle", "Wallenbachstr"),
	WASSERBILLIGERSTR("wbill", "Wasserbilliger Str"),
	WASSERWE("waweg", "Wasserwe"),
	WEISMARKPFAHLWEIHE("WEI", "Weismark-Pfahlweihe"),
	WENZELBACHSTR("wenze", "Wenzelbachstr"),
	WERDINGSTR("werdi", "Werdingstr"),
	WESTBAHNHO("WBF", "Westbahnho"),
	WILHLEUSCHNERSTR("WLE", "Wilh.-Leuschner-Str"),
	WINKIRCH("WDK", "Win-Kirch"),
	WINLINDENSTR("wdlin", "Win-Lindenstr"),
	WINWEINBERGSWE("wdwei", "Win-Weinbergswe"),
	WISPORTSTR("wispo", "Wisportstr"),
	WOLFSBER("WOB", "Wolfsber"),
	WOLKERSTR("wolke", "Wolkerstr"),
	ZEWENFRIEDHO("ZEF", "Zewen-Friedho"),
	ZUMHELLBER("hellb", "Zum Hellber"),
	ZUMROEMERSPRUDE("sprud", "Zum Roemersprude"),
	ZURLAUBENERUFE("ZUR", "Zurlaubener Ufe"),
	ZURMAIENERSTRNORD("zurma", "Zurmaiener Str.Nord");
	
	private String stopCode;
	private String name;
	
	BusStop(String stopCode, String name) {
		this.stopCode = stopCode;
		this.name = name;
	}
	
	public String getStopCode() {
		return this.stopCode;
	}
	
	public String getName() {
		return this.name;
	}
	
	public String toString() {
		return this.name;
	}
	
	public static BusStop getBusStopByStopCode(String stopCode) {
		for(BusStop b : BusStop.values()) {
			if(b.getStopCode().equals(stopCode)) {
				return b;
			}
		}
		
		return null;
	}

    public static BusStop getBusStopByName(String name) {
        for(BusStop b : BusStop.values()) {
            if(b.getName().equals(name)) {
                return b;
            }
        }

        return null;
    }
}
